apiVersion: apps/v1
kind: Deployment
metadata:
  name: custumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: santanarael/custumer-fiap
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: postech.ufjbi3d.mongodb.net
            - name: DB_PORT
              value: '27017'
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: 'postech'
            - name: DB_NAME
              value: postech_custumer
          resources:
            requests:
              memory: '128Mi' # Mem칩ria inicial / MI = milicores (1 core = 1000 milicores)
              cpu: '100m' # CPU inicial
            limits:
              memory: '628Mi' # Limite m치ximo de mem칩ria
              cpu: '300m' # Limite m치ximo de CPU  / M = megabytes
---
apiVersion: v1
kind: Service
metadata:
  name: custumer-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 32323
      targetPort: 3001
  type: LoadBalancer